### ISSUE TITLE
Create a new client route

### ISSUE THREAD

**Issue by bitcoinbrisbane** [Transitional-Legal/ftc-client-api#1]
**User Story**
- As a new TL customer,
- When I create an account,
- Then I get a verification email

/contact as a post

=> save email and password to our postgres
=> Update action step with new contract

**Comment by bitcoinbrisbane** [comment]
Need to send the welcome email vai O365 too.

**Comment by tommycp3** [comment]
[1. read the inbox with office 365](https://github.com/OfficeDev/office-content/blob/main/rest-api/node/getting-started-Office-365-APIs-node.md)
